version: "3.5"
services: 

    php:
      container_name: pma-php
      restart: always
      build: .
      links:
        - mysql

    web:
      container_name: pma-web
      restart: always
      image: nginx:latest
      ports:
        - "8880:80"

    mysql:
      container_name: pma-mysql
      restart: always
      image:  mysql:5.7
      ports:
        - "3316:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./storage/dump.sql:/storage/dump.sql
        - ./scripts/load.sh:/docker-entrypoint-initdb.d/load.sh

    phpmyqdmin:
      container_name: pma
      restart: always
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:db
      ports:
        - "8082:80"



